services:
  - type: web
    name: whatismyip-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://whatismyip.world,https://www.whatismyip.world
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: veremij@ukr.net
      - key: ADMIN_PASSWORD
        value: Qwerty!67890
    healthCheckPath: /health
